### ISSUE TITLE
Incorrect structure config for pre-1.16 shipwrecks results in wrong position values

### ISSUE THREAD

**Issue by AeroAstroid** [Cubitect/cubiomes#113]
Reproducible by using the getStructurePos function to find a shipwreck in any version from MC_1_13 to MC_1_15 (or by using cubiomes-viewer to locate one in these versions), loading up the seed in-game in the corresponding version, and verifying that the reported positions differ from the result of /locate Shipwreck.

For instance, seed 7568941961015246499 is described by cubiomes-viewer as having a shipwreck at 32, 32 in any of these three versions, whereas for all of them the correct location for that region is 112, 112.

**Comment by Cubitect** [comment]
Thanks for the report and fix.
