### ISSUE TITLE
getBiomeCenters returns wrong biome sizes

### ISSUE THREAD

**Issue by Gaider10** [Cubitect/cubiomes#122]
Example in cubiomes viewer:
MC 1.20
seed: 7335000078560539927
Large biomes
Y: 64
x1: 2313 z1: 1533 x2: 2924 z2: 2133

Biome Statistics scale 1:4 Mushroom Fields count: 4730
![image](https://github.com/user-attachments/assets/67226ef7-08a0-4a46-b912-c059c34d86b1)
Biome Locate Mushroom Fields area @ 1:4: 1 + 9206
![image](https://github.com/user-attachments/assets/318fe942-b0e6-4a8e-b8d0-db776387809b)

This happens because in [floodFillGen](https://github.com/Cubitect/cubiomes/blob/0af31b4e7eeb14a58c2bd9a4c4c68b97b4a7d6e8/finders.c#L4021) the same position can be added to the queue multiple times before one of them gets popped and the position's ids entry gets set to INT_MAX.
Checking for ids[k] == INT_MAX before processing each popped queue entry fixes the issue.

**Comment by Cubitect** [comment]
Thanks for the report. Fixed in the 4.1 release.
