### ISSUE TITLE
Proposed changes for more_finders.

### ISSUE THREAD

**Issue by Cubitect** [Cubitect/cubiomes#13]
I don't know of a better way to make a code suggestion for a fork repository, so I'm making this issue. [Here](https://github.com/Cubitect/cubiomes/tree/more_finders) is a branch for `more_finders` with the API changes applied and I fixed some compiler warnings.

**Comment by fwiffo** [comment]
Oh thanks! I didn't expect you to try to maintain my hacky branch. It's not something I intended to inflict on anyone else. Feel free to merge any parts you want though.
