### ISSUE TITLE
Setting MCver 1.14 returns invalid BiomeID 297 occasionally

### ISSUE THREAD

**Issue by pisto** [Cubitect/cubiomes#23]
testcase: seed 5010, position -3000,-3000.

Amidst for that seed and location shows biome bamboo_jungle (version 1.14), and jungle (version 1.13), which makes sense as bamboo is a variation of jungle.

297-128=169 is bamboo_jungle_hills, so I supposed it's a broken interplay between `mapAddBamboo()` and `mapHills113()`.

Unfortunately I don't have the expertise to debug this further.

Note that I'm using getBiomeAtPos().

**Comment by Badel2** [comment]
Your intuition was correct, the issue was in mapHills113 when the biome id is set to bamboo_jungle_hills. PR #24 contains a simple fix, can you try if it works for you?

**Comment by pisto** [comment]
it appears correct, thank you.

Please don't kill your forked repo as I'm going to reference it in [minecrack](https://github.com/pisto/minecrack) until this gets merged
