### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by IChris4o** [Cubitect/cubiomes#27]
Hey there im not sure if this is for here but ide like to ask how do i start up and use the quad witch searcher because everything i download is some files and im couldnt find anything here on the thread about wath program i should use to start it up. So if someone can help me i would be grateful.

**Comment by Cubitect** [comment]
Have you compiled the code?
The command line for the quad-hut searcher is:

`find_quadhuts [regionX] [regionZ] [mcversion]`

So as an example, to get a list of seeds with a quad-hut about the origin in 1.16 you would run:

`$ ./find_quadhuts 0 0 116`

**Comment by IChris4o** [comment]
I dont know where to run that code! Is there  a way to search a seed i already have for quad huts?

**Comment by he77789** [comment]
You run that aforemented command in the terminal.

If you already have a set seed and you want to find quad witch huts in it, use GetStructurePos with the lower 48 bits of your seed and isViableStructurePos with the full seed. You can have it generate a list of witch huts within X blocks of the origin, then you can chexk for quad witch huts with that data. That requires actually writing C code though. This is mainly a library, not a full fledged polished program.
