### ISSUE TITLE
Feature request: World Spawn Point

### ISSUE THREAD

**Issue by Boobies** [Cubitect/cubiomes#40]
I've noticed that the world spawn point is not always at (0, 0) but wasn't sure exactly how it worked so was afraid it's decided late in the generation process. However, I'm told by code diggers that it is actually not and that it's, as far as I understand, a matter of finding an appropriate biome near the center and if not then (0, 0) is used. Could we have a function to help with this?

**Comment by Cubitect** [comment]
There are already two functions for this `getSpawn()` and `estimateSpawn()` in `finders.h`. You are correct that the world spawn is mostly determined by a random walk until a valid biome is found, however an additional requirement is that the top block is a grass or podzol block. If you want to test millions of seeds, this is one of the most expensive world properties you can test for  (except maybe stronghold placement) even without the grass requirement, and I would recommend looking for other criteria first. The `estimateSpawn()` function only tests for the presence of a valid biome, while `getSpawn()` is somewhat more accurate and tries to consider the likelihood for a grass block. However, it is far from perfect. A fully accurate test would require to actually generate the terrain.
