### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by bhjk1** [Cubitect/cubiomes#42]
I tried to run the example code given in the README file using Visual Studio, but I couldn't get it to work. I got hundreds of errors from the finders.h file, so I assume that I didn't install cubiomes correcty, but I have no idea what I did wrong.

**Comment by Cubitect** [comment]
Sorry for the late reply. I don't have Windows or Visual Studio so I can't say for sure, but I recall that Visual Studio only supports C89, while cubiomes is written in an intersection subset of C99 and C++11. You might have success by changing the compiler in the makefile to `g++`.

**Comment by duki** [comment]
Try installing tdm-gcc and compiling cmd-line, after changing **typedef unsigned int WORD**  into **typedef unsigned short WORD** in **sha256.h** or by opting to globally change _.../mingw/include/minwindef.h_  **typedef unsigned int WORD** into **typedef unsigned short WORD**. Could try the first fix withing Visual Studio. This issue should now be closed.
