### ISSUE TITLE
Ocean Monument False Positives in 1.8

### ISSUE THREAD

**Issue by Pineapplecake** [Cubitect/cubiomes#43]
The `isViableStructurePos` function is unreliable for ocean monuments in 1.8 world generation. In my test program [monument_test.c](https://gist.github.com/Pineapplecake/2c9756a7defdda47d9d9762f3a5021ff) 5 of the 10 output seeds do not have an ocean monument in region (0,0). This does not seem to be the case with 1.16 world generation, where all 4 output seeds do have an ocean monument in the desired region.

**Comment by Cubitect** [comment]
Thank you for reporting. The biome validation for ocean monuments should be fixed now.
