### ISSUE TITLE
Features Request: Fortresses

### ISSUE THREAD

**Issue by Boobies** [Cubitect/cubiomes#49]
I've noticed you've started working on Nether generation. Presumably, this means we'll be able to look for fortresses soon. Would it be possible to also look into structure generation? A common thing people might look for is fortresses with 5 four-way crossings in soul sand valleys, in order to build farms. However, I'm not sure whether the generation of the structure is dependent on further stages of the terrain generation; if so, it might not be feasible.

**Comment by wendavid552** [comment]
As you may see in https://github.com/Gaider10/CrossroadFinder, you could try adding the feature of looking for certain fortresses in certain biomes with this library.

**Comment by Cubitect** [comment]
Fortress piece generation can be done with `getFortressPieces()`.
An implementation of a 2x2 crossing finder is part of cubiome-viewer.
