### ISSUE TITLE
A few bugs I might want to list (please let it open)

### ISSUE THREAD

**Issue by hube12** [Cubitect/cubiomes#51]
This is mainly a list of the current bugs with your lib and common pitfall (we address them in biomeutils)
- Stronghold since 1.16+ do not use bamboo and bamboo jungle hills (please remove them from the height https://github.com/Cubitect/cubiomes/blob/master/finders.c#L1000 since they are positive for 1.16+) https://github.com/KaptainWutax/FeatureUtils/blob/master/src/main/java/kaptainwutax/featureutils/structure/Stronghold.java#L25
- AreSimilar is wrong for 1.16.2 since the badlands plateau got a new category, https://github.com/KaptainWutax/BiomeUtils/blob/d3e707210bd14883836ee61b6a043d3ec4f76f51/src/main/java/kaptainwutax/biomeutils/layer/shore/EaseEdgeLayer.java#L50 and https://github.com/KaptainWutax/BiomeUtils/blob/d3e707210bd14883836ee61b6a043d3ec4f76f51/src/main/java/kaptainwutax/biomeutils/Biome.java#L133 are needed, for instance this test can be used (before voronoi layer) https://github.com/KaptainWutax/BiomeUtils/blob/master/src/test/java/kaptainwutax/v1_16_5/Overworld.java#L90

Making those two changes will allow you to correct your stronghold accuracy (for those specific cases only tho)
Example:
Load 1437905338718953247 and go at (x,z)=(-20480,808) you can use Minemap https://github.com/hube12/MineMap/releases/tag/1.31 , load both 1.16.1 and 1.16.2 you will get those 2 differents ones 
1.16.2+: /tp @s -20040 ~ 1352
1.16.1- :  /tp @s -20392 ~ -120

![1 16 2+](https://user-images.githubusercontent.com/26262005/114102496-b5be6600-98c7-11eb-9ad4-c564953ebfeb.PNG)
![1 16 1-](https://user-images.githubusercontent.com/26262005/114102499-b656fc80-98c7-11eb-9e8a-57022be3db20.PNG)

**Comment by hube12** [comment]
Your stronghold is above the shipwreck and the red cross (buried treasure) 
Here a picture before I fix the issue in biomeutils
![wqeqweqwe](https://user-images.githubusercontent.com/26262005/114102602-df778d00-98c7-11eb-82b1-70c17ae08a9a.PNG)

**Comment by Cubitect** [comment]
Thanks for the report.
These points should be fixed for a while now, is there still reason to keep this open?

I took the liberty to test biomeutils using the references I generated with a fabric mod and found a couple of
bugs there as well. Some examples (at scale 1:4, `'full'`):

1.16: seed=84 pos=(-12,-3) is 37  but should be 39
(Your solution to the mesa -> badlands categorization issue might not be entirely correct)

1.10: seed=48 pos=(-16,-2) is 155 but should be 156
(MC-98995?)


In case you want to check against my references here is a stripped version of 
the code I used (analogous to `getRef()` in `cubiomes/tests.c`):

```
import java.io.IOException;
import java.io.PrintWriter;

import kaptainwutax.biomeutils.source.OverworldBiomeSource;
import kaptainwutax.mcutils.version.MCVersion;

public class Tests
{
    static int hash32(int x)
    {
        x ^= x >>> 15;
        x *= 0xd168aaad;
        x ^= x >>> 15;
        x *= 0xaf723597;
        x ^= x >>> 15;
        return x;
    }
    
    // use a reasonably straightforwards algorithm to test different seeds and
    // positions to produce a reference hash
    static long getRef(MCVersion mc, long bits, String path)
    {
        int r = 1 << (bits-1);
        int h = 0;
        PrintWriter wr = null;
        try {
            if (path != null)
                wr = new PrintWriter(path, "UTF-8");
        } catch (IOException e) {}
        
        for (int x = -r; x < r; x++)
        {
            for (int z = -r; z < r; z++)
            {
                long s = (long)( (z << bits) ^ x );
                OverworldBiomeSource src = new OverworldBiomeSource(mc, s);
                int id = src.full.sample(x, 0, z);
                if (wr != null)
                    wr.write(String.format("%5d%6d%4d\n", x, z, id));
                h ^= hash32( (int) s ^ (id << 2*bits) );
            }
        }
        if (wr != null)
            wr.close(); 
        return (long)h & 0xffffffffL;
    }
    
    public static void main(String[] args)
    {
        // see cubiomes/tests.c for more expected hashes
        long h = getRef(MCVersion.v1_9, 6, null);
        System.out.printf("%08x: %s\n", h, h == 0xe27a45a2L ? "OK :)" : "Not OK");
    }
}
```

**Comment by hube12** [comment]
Thanks I will look into those, I will open a new issue whenever I find another issue ;)

**Comment by hube12** [comment]
![12313212332](https://user-images.githubusercontent.com/26262005/118715571-11173880-b824-11eb-8680-800594243fe2.PNG)
for the 1.16 stuff, no issues there, only 1.16.1- vs 1.16.2+

**Comment by hube12** [comment]
![23131212323](https://user-images.githubusercontent.com/26262005/118715648-2724f900-b824-11eb-8c3c-64aa0eb592af.PNG)
