### ISSUE TITLE
Full-generation including buildings internals

### ISSUE THREAD

**Issue by maxsupermanhd** [Cubitect/cubiomes#52]
Since Mojang released mappings we can now attempt to recreate all details of structures and how they are generated. Will this be added in future?

**Comment by Cubitect** [comment]
I'm not sure but [cuberite](https://github.com/cuberite/cuberite) is a full Minecraft server implementation and might have something along those lines, but I have not looked into how accurate its world generation is.

There are no plans for this for cubiomes. The focus is primarily on biome generation and it supports most structure placements. Aspects that have block-level dependencies would require full world generation, which would be a much much larger project. 

The mappings have never actually been an issue, I used to use the obfuscated code as reference when snapshots came out.
