### ISSUE TITLE
Macro 'U' conflicts with identifiers in other libraries.

### ISSUE THREAD

**Issue by ioctl0** [Cubitect/cubiomes#59]
cubiomes defines a macro 'U' to abbreviate __builtin_unlikely. This is convenient, but precludes using 'U' as a variable name in any code included alongside cubiomes. Notably "U" is frequently used as a template parameter name in C++ code. Adding "#undef U" after including cubiomes is, of course, a workaround, but is suboptimal.

**Comment by Cubitect** [comment]
Renamed to `L` and `U` to `likely` and `unlikely` respectively.
