### ISSUE TITLE
Stronghold location sometimes wildly off in 1.18

### ISSUE THREAD

**Issue by orlp** [Cubitect/cubiomes#60]
Problematic seed: `8606696102824824313`

Program reports these strongholds:
```
Stronghold #1  : (  1884,   1876)
Stronghold #2  : ( -2272,    840)
Stronghold #3  : (   468,  -2172)
Stronghold #4  : ( -3468,   3908)
Stronghold #5  : ( -4784,   -776)
Stronghold #6  : ( -1828,  -5080)
Stronghold #7  : (  3820,  -4216)
Stronghold #8  : (  4692,   1000)
Stronghold #9  : (  1780,   5224)
Stronghold #10 : (  5580,  -6176)
Stronghold #11 : (  8520,  -1836)
Stronghold #12 : (  7224,   3224)
```

Checking in-game with `/locate stronghold` we find a stronghold at -1400, 424 (and it is actually there):

![image](https://user-images.githubusercontent.com/202547/143781291-750b56bc-fa73-47fd-bef0-e65772e694b3.png)

[Chunkbase](https://www.chunkbase.com/apps/seed-map#8606696102824824313) gets this seed right when put in the experimental 1.18 mode.

Repro program (identical to example in readme, apart from seed):

```c
#include "finders.h"
#include <stdio.h>

int main()
{
    int mc = MC_1_18;
    uint64_t seed = 8606696102824824313LL;

    // Only the first stronghold has a position which can be estimated
    // (+/-112 blocks) without biome check.
    StrongholdIter sh;
    Pos pos = initFirstStronghold(&sh, mc, seed);

    printf("Seed: %" PRId64 "\n", (int64_t) seed);
    printf("Estimated position of first stronghold: (%d, %d)\n", pos.x, pos.z);

    Generator g;
    setupGenerator(&g, mc, 0);
    applySeed(&g, 0, seed);

    pos = getSpawn(&g);
    printf("Spawn: (%d, %d)\n", pos.x, pos.z);

    int i, N = 12;
    for (i = 1; i <= N; i++)
    {
        if (nextStronghold(&sh, &g) <= 0)
            break;
        printf("Stronghold #%-3d: (%6d, %6d)\n", i, sh.pos.x, sh.pos.z);
    }

    return 0;
}
```

**Comment by Cubitect** [comment]
Strongholds are very problematic in 1.18-rc3 because of [MC-241546](https://bugs.mojang.com/browse/MC-241546) and the positions might not even be consistent for the same seed inside Minecraft because of it. Chunkbase also gets it wrong if you check one of the outer strongholds. It worked for my test seeds, but I will investigate if the accuracy can be improved (although if one is wrong chances are all the following are as well). Thanks for the report though.

**Comment by orlp** [comment]
I see, I didn't know it was messed up at the origin. Hope it gets resolved soon.

**Comment by Cubitect** [comment]
It turns out my method of dealing with that MC bug does work after all, but I had two other issues that could result in wrong stronghold positions. This should be fixed now.
