### ISSUE TITLE
Cannot load seed lists

### ISSUE THREAD

**Issue by Boobies** [Cubitect/cubiomes#63]
Whenever a file gets selected with a seed list, it says "Failed to load seed list from file". The file simply contains the a paste grabbed from cubiomes-viewer.

**Comment by Boobies** [comment]
Uhm. This was meant for cubiomes-viewer. My bad.

**Comment by Cubitect** [comment]
There were problems when a seed list was no longer present it would quietly fail to load on startup and then prevent all further loading attempts. So I think this was fixed in 2.0.
