### ISSUE TITLE
What is regX and regZ in getStructurePos?

### ISSUE THREAD

**Issue by DeexCoding** [Cubitect/cubiomes#64]

**Comment by Badel2** [comment]
Region X and Region Z. I believe that the way minecraft generates structures, there is one structure per region, and the `getStructurePos` returns the coordinates of that one structure.

You can find a better description in the README:

https://github.com/Cubitect/cubiomes/blob/9d0b692d1f1158ed46fc1523b2e7d47fc196de75/README.md#structure-generation

Or in the function documentation:

https://github.com/Cubitect/cubiomes/blob/0cd6e8134a0d257685867f8a77f5cd6c01ab8353/finders.h#L309
