### ISSUE TITLE
Is there a way to check where the end portal frame generates within a stronghold?

### ISSUE THREAD

**Issue by Sentostalo** [Cubitect/cubiomes#66]
I am aware that stronghold staircases can be found with the `StrongholdIter`. However, is there any way to check where the end portal frame would generate for that given stronghold?

**Comment by Cubitect** [comment]
Unfortunately no, the generation of the stronghold, including the portal room, depend on the blocks in the world and require the full world generation. Cubiomes is limited to features that can be determined from the biomes.
