### ISSUE TITLE
Support for Beta 1.8

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes#67]
The world generation in Minecraft 1.0 and 1.1 is not significantly different from Beta 1.8, quite similar. Beta 1.8 uses generation similar to MC 1.0 and MC 1.1, as the latter's generator was introduced in Beta 1.8 
![image](https://user-images.githubusercontent.com/23464599/170136621-e10bc47b-60cb-40bd-9fc7-70000c8cfc7c.png)

**Comment by KaiSandstrom** [comment]
I've been messing around with the MC and Cubiomes code for the last few days trying to figure out the specific differences between b1.8 and r1.0 continent generation, and I finally have it producing accurate maps that are 1:1 identical to what AMIDST outputs for Beta 1.8. I'll make a fork of this repo sometime in the next few days and keep working on it until the rest of Cubiomes' relevant features work accurately for Beta 1.8 as well -- if I end up finishing it I'll make a pull request.

**Comment by KaiSandstrom** [comment]
Made the pull request. If the changes are merged, Cubiomes will support Beta 1.8.
