### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by F1rsi** [Cubitect/cubiomes#71]
Does the version of minecraft affect the speed of finding seeds on the spawn?

**Comment by Cubitect** [comment]
The world spawn algorithm changed several times over the versions and biome generation also changes. So yes, how long it takes to find spawn very much depends on the version. The most notable changes occurred in 1.7, 1.13 and 1.18.

**Comment by F1rsi** [comment]
Good, Thank you for your reply.
