### ISSUE TITLE
File is a Folder

### ISSUE THREAD

**Issue by StealthMeister1** [Cubitect/cubiomes#85]
First time getting this things and apparently the folder that's named "cubiomes" is actually supposed to be an application/.exe file. It's not. What the hell do I do and if I can't do anything, can someone else fix it?

**Comment by Cubitect** [comment]
Cubiomes is a software library, as is clearly stated in the description.
There is a GUI application [cubiomes-viewer](https://github.com/Cubitect/cubiomes-viewer), if that is what you are looking for.

**Comment by StealthMeister1** [comment]
I had got the viewer and the file was a folder. I appreciate you treating me like a child though 🖕

**Comment by StealthMeister1** [comment]
> Cubiomes is a software library, as is clearly stated in the description. There is a GUI application [cubiomes-viewer](https://github.com/Cubitect/cubiomes-viewer), if that is what you are looking for.

I had got the viewer and the file was a folder. I appreciate you treating me like a child though 🖕
