### ISSUE TITLE
Mutated biomes generate differently in 1.13

### ISSUE THREAD

**Issue by fwiffo** [Cubitect/cubiomes#9]
There are some differences in the generation of mutated biomes in 1.13 that are marked as WAI. [MC-125037](https://bugs.mojang.com/browse/MC-125037) discusses the details, but apparently the mutated attribute no longer leaks into neighboring biomes. That's more-or-less consistent with what appears in the game and in Amidst.

This obviously also indirectly affects structure generation. For example, for seed -8245890327006074204, there is a taiga village at -876,1332 in 1.13, but none in 1.12.2 (where it's a taiga M biome instead of regular taiga).

As far as I can tell, this *only* affects the boundaries of mutated biomes; any boundaries between regular biomes is unaffected.

**1.12.2**
![-8245890327006074204_1_12_2](https://user-images.githubusercontent.com/169511/42423249-2cb2c4c0-82ac-11e8-9f30-fb186d27a0fb.png)

**1.13-pre4**
![-8245890327006074204_1_13](https://user-images.githubusercontent.com/169511/42423250-33978582-82ac-11e8-8aee-ff2ceb70790b.png)

**Comment by Cubitect** [comment]
Thanks for reminding me of this. I noticed this a while back, but it wasn't marked as indented back then. I'll look into how to update the layers accordingly.
