### ISSUE TITLE
[Beta 1.7] Small fringes of rainforest erroneously generating around tundra biomes

### ISSUE THREAD

**Issue by KaiSandstrom** [Cubitect/cubiomes#91]
This bug was caused by one of the changes made to the master branch between PR #87 and PR #90. The first image below was created in my fork using the same code submitted for #90. The second was created after syncing the fork with origin master and recompiling. The third image shows the difference.

I haven't thoroughly dug into the changes, but I suspect this was caused by the changes in biome_tree.c to `getOldBetaBiome()` and the Beta 1.7 biome lookup table.

![fringepre](https://user-images.githubusercontent.com/76536266/216837432-0644dc71-4d8f-4235-b2be-80a100a5ac64.png)
![fringepost](https://user-images.githubusercontent.com/76536266/216837452-6a16ad72-370b-49b8-ae55-537b29554d24.png)
![fringediff](https://user-images.githubusercontent.com/76536266/216837460-46f591ce-53fd-4a77-932d-7ea368f25b03.png)

**Comment by Cubitect** [comment]
My bad. I rearranged the biome ID mapping to an ascending order but made a mistake with the substitution.
I'm surprised that I didn't get a warning from my testing code that the output had changed...

**Comment by KaiSandstrom** [comment]
That did the trick
